services:
  db:
    image: postgres:15-alpine
    container_name: alphadash_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=alphadash_user
      - POSTGRES_PASSWORD=alphadash_pass
      - POSTGRES_DB=alphadash_db
    restart: unless-stopped

volumes:
  postgres_data:
