services:
  db:
    image: postgres:15-alpine
    container_name: alphadash_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=alphadash_user
      - POSTGRES_PASSWORD=alphadash_pass
      - POSTGRES_DB=alphadash_db
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: alphadash_backend_container
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://alphadash_user:alphadash_pass@db:5432/alphadash_db"
      SECRET_KEY: "${SECRET_KEY}"
      ACCESS_TOKEN_EXPIRE_MINUTES: "${ACCESS_TOKEN_EXPIRE_MINUTES:-30}"
      PROJECT_NAME: "${PROJECT_NAME:-alpha-dash}"
      ALGORITHM: "${ALGORITHM:-HS256}"

volumes:
  postgres_data:
