services:
  db:
    image: postgres:15-alpine
    container_name: alphadash_db_container
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=alphadash_user
      - POSTGRES_PASSWORD=alphadash_pass
      - POSTGRES_DB=alphadash_db
    restart: unless-stopped

  redis_cache:
    image: redis:7-alpine
    container_name: alphadash_redis_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_cache_data:/data
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: alphadash_backend_container
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - redis_cache
    environment:
      DATABASE_URL: "postgresql://alphadash_user:alphadash_pass@db:5432/alphadash_db"
      SECRET_KEY: "${SECRET_KEY}"
      ACCESS_TOKEN_EXPIRE_MINUTES: "${ACCESS_TOKEN_EXPIRE_MINUTES:-30}"
      PROJECT_NAME: "${PROJECT_NAME:-alpha-dash}"
      ALGORITHM: "HS256"
      REDIS_HOST: "redis_cache"
      REDIS_PORT: "6379"
      ALPHA_VANTAGE_API_KEY: "${ALPHA_VANTAGE_API_KEY}"

  celery_worker:
    build: ./backend
    container_name: alphadash_celery_worker
    command: celery -A app.core.celery_app worker -l info -Q celery
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - redis_cache
    environment:
      DATABASE_URL: "postgresql://alphadash_user:alphadash_pass@db:5432/alphadash_db"
      REDIS_HOST: "redis_cache"
      REDIS_PORT: "6379"
      ALPHA_VANTAGE_API_KEY: "${ALPHA_VANTAGE_API_KEY}"
      SECRET_KEY: "${SECRET_KEY}" 
      ALGORITHM: "HS256"
      PROJECT_NAME: "${PROJECT_NAME:-alpha-dash}"
      ACCESS_TOKEN_EXPIRE_MINUTES: "${ACCESS_TOKEN_EXPIRE_MINUTES:-30}"

  celery_beat:
    build: ./backend
    container_name: alphadash_celery_beat
    command: celery -A app.core.celery_app beat -l info -s /app/celerybeat-schedule 
    volumes:
      - ./backend:/app 
    depends_on:
      - db
      - redis_cache
    environment:
      DATABASE_URL: "postgresql://alphadash_user:alphadash_pass@db:5432/alphadash_db"
      REDIS_HOST: "redis_cache"
      REDIS_PORT: "6379"
      ALPHA_VANTAGE_API_KEY: "${ALPHA_VANTAGE_API_KEY}"
      SECRET_KEY: "${SECRET_KEY}"
      ALGORITHM: "HS256"
      PROJECT_NAME: "${PROJECT_NAME:-alpha-dash}"
      ACCESS_TOKEN_EXPIRE_MINUTES: "${ACCESS_TOKEN_EXPIRE_MINUTES:-30}"

  frontend:
    build: ./frontend
    container_name: alphadash_frontend_container
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules 
    depends_on:
      - backend
    stdin_open: true
    tty: true

volumes:
  postgres_data:
  redis_cache_data:
