name: Backend CI

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci.yml'

jobs:
  build-and-test:
    name: Build and Test Backend
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    env:
      DATABASE_URL: "postgresql://testuser:testpass@localhost:5432/testdb"
      SECRET_KEY: "test_secret_key_for_ci_0123456789abcdefghijklmnopqrstuvwxyz"
      PROJECT_NAME: "AlphaDash Test"
      ACCESS_TOKEN_EXPIRE_MINUTES: "30"
      ALGORITHM: "HS256"
      ALPHA_VANTAGE_API_KEY: "DUMMY_AV_KEY_FOR_CI"
      REDIS_HOST: "localhost"
      REDIS_PORT: "6379"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Lint with Ruff
        run: |
          python -m ruff check . --output-format=github 
      
      - name: Format Check with Black
        run: |
          python -m black --check .

      - name: Run unit tests with Pytest
        run: |
          python -m pytest 
          
      - name: Build Docker image
        run: |
          docker build -t alpha-dash-backend:ci-${{ github.sha }} .
